forum_project/apps/roleplay_user_and_login/urls.py
from .views import RegistrationView, CabinetView, InventoryView, LoginView, LogoutView, activate
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView


app_name = 'roleplay_user_and_login'
urlpatterns = [
	path('login/', LoginView.as_view(), name='login'),
	path('logout/', LogoutView.as_view(), name='logout'),
	path('signup/', RegistrationView.as_view(), name='signup'),
	path('activate/<uidb64>/<token>/', activate, name='activate'),  
	path('reset/', auth_views.PasswordResetView.as_view(
		template_name='roleplay_user_and_login/pw_reset.html',
		success_url='done/'
	), name='reset'),
	path('reset/done/', TemplateView.as_view(
		template_name='roleplay_user_and_login/pw_reset_done.html'
	), name='reset_done'),
	path('cabinet/', CabinetView.as_view(), name='cabinet'),
	path('inventory/<int:pk>', InventoryView.as_view(), name='inventory'),
	path('', include('django.contrib.auth.urls'))
]

forum_project/forum/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.core.urls')),
    path('api/v1/', include('apps.api.v1.urls')),
    path('', include('apps.roleplay_user_and_login.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

forum_project/apps/roleplay_user_and_login/models.py
# users/models.py
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser, PermissionsMixin
)
from django.db import models
from .tasks import send_mail_task

class MyUserManager(BaseUserManager):
    def create_user(self, username, email, password=None):
        if not username:
            raise ValueError('Users must have username')
        if not email:
            raise ValueError('Users must have mail')
        user = self.model(
            username=username,
            email=email
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, email, password):
        user = self.create_user(
            username=username,
            email=email,
            password=password,
        )
        user.is_admin = True
        user.save(using=self._db)
        return user


class MyUser(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(max_length=40, unique=True)
    email = models.EmailField(unique=True)
    phone = models.CharField(blank=True, max_length=20)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    objects = MyUserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    def __str__(self):
        return self.username

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        return self.is_admin
    
    def send_user_mail(self, subject, message):
        send_mail_task.delay(subject, message, self.email)

class Project(models.Model):
    name = models.CharField(max_length=64)

    def __str__(self):
        return self.name
    

class Inventory(models.Model):
    user = models.ForeignKey(MyUser, on_delete=models.CASCADE)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)

    @classmethod
    def get_user_inventorys(cls, user):
        return cls.objects.filter(user=user)

class Item(models.Model):
    inventory = models.ForeignKey(Inventory, on_delete=models.CASCADE)
    name = models.CharField(max_length=124)
    description = models.TextField(null=True, blank=True)
    image = models.ImageField(null=True, blank=True)
    price = models.IntegerField(default=0, blank=True)
    in_stock = models.BooleanField(default=True, blank=True)

    @classmethod
    def get_inventory_items(cls, inventory):
        return cls.objects.filter(inventory=inventory)
    
    def __str__(self):
        return self.name

forum_project/apps/roleplay_user_and_login/forms.py
from django import forms
from django.contrib import admin
from django.contrib.auth.models import Group, AbstractUser
from django.contrib.auth.admin import UserAdmin as BaseUserAdmin
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from .models import MyUser


class UserCreationForm(forms.ModelForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = MyUser
        fields = ['username', 'email']

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class UserChangeForm(forms.ModelForm):
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = MyUser
        fields = ('username', 'email', 'password', 'is_active', 'is_admin')

    def clean_password(self):
        # Regardless of what the user provides, return the initial value.
        # This is done here, rather than on the field, because the
        # field does not have access to the initial value
        return self.initial["password"]


class UserAdmin(BaseUserAdmin):
    # The forms to add and change user instances
    form = UserChangeForm
    add_form = UserCreationForm

    # The fields to be used in displaying the User model.
    # These override the definitions on the base UserAdmin
    # that reference specific fields on auth.User.
    list_display = ('username', 'email', 'is_admin')
    list_filter = ('is_admin',)
    fieldsets = (
        (None, {'fields': ('username', 'email', 'password')}),
        ('Permissions', {'fields': ('is_admin',)}),
    )
    # add_fieldsets is not a standard ModelAdmin attribute. UserAdmin
    # overrides get_fieldsets to use this attribute when creating a user.
    add_fieldsets = (
        (None, {
            'classes': ('wide',),
            'fields': ('username', 'email', 'password1', 'password2')}
        ),
    )
    search_fields = ('username',)
    ordering = ('username',)
    filter_horizontal = ()


# Now register the new UserAdmin...
admin.site.register(MyUser, UserAdmin)
# ... and, since we're not using Django's built-in permissions,
# unregister the Group model from admin.
admin.site.unregister(Group)

forum_project/apps/roleplay_user_and_login/views.py
from django.contrib.auth import login, logout, authenticate
from django.shortcuts import render, redirect
from django.views.generic import View, TemplateView, ListView, DetailView, RedirectView, CreateView, FormView
from django.http.response import JsonResponse
from django.urls import reverse_lazy
from .models import Inventory, Item, MyUser
from ..core.models import Comment
from .forms import UserCreationForm
from django.contrib.auth.forms import AuthenticationForm
from .tokens import account_activation_token
from django.http import HttpResponse  
from django.shortcuts import render  
from django.contrib.sites.shortcuts import get_current_site  
from django.utils.encoding import force_bytes, force_text  
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode  
from django.template.loader import render_to_string
from django.contrib.auth.mixins import LoginRequiredMixin

class RegistrationView(FormView):
    template_name = 'roleplay_user_and_login/signup.html'
    form_class = UserCreationForm
    success_url = reverse_lazy('core:index')
    def form_valid(self, form):
        print('form is valid')
        user = form.save(commit=False)
        user.is_active = False
        user.save()
        print('user saved')
        current_site = get_current_site(self.request)
        mail_subject = 'Activate your blog account.'
        message = render_to_string(
            'roleplay_user_and_login/acc_active_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid':urlsafe_base64_encode(force_bytes(user.pk)),
                'token':account_activation_token.make_token(user),
            }
        )
        user.send_user_mail(mail_subject, message)
        return render(self.request, 'roleplay_user_and_login/confirm_email.html')


class LoginView(FormView):
    template_name = 'roleplay_user_and_login/login.html'
    form_class = AuthenticationForm
    success_url = reverse_lazy('core:index')

    def form_valid(self, form):
        user = form.get_user()
        login(self.request, user)
        return super().form_valid(form)

class LogoutView(RedirectView):
    pattern_name = 'core:index'

    def get_redirect_url(self, *args, **kwargs):
        logout(self.request)
        return super().get_redirect_url(*args, **kwargs)


class CabinetView(LoginRequiredMixin, TemplateView):
    login_url = '/login/'
    template_name = 'roleplay_user_and_login/cabinet.html'

    def get_context_data(self, **kwargs):
        n_of_comments = Comment.objects.filter(user=self.request.user).count()
        ctx = {
            'inventory': Inventory.get_user_inventorys(self.request.user), 
            'number_of_comments': n_of_comments
        }
        return ctx

class InventoryView(CreateView):
    template_name = 'roleplay_user_and_login/inventory.html'
    model = Inventory
    pk_url_kwarg = 'pk'

    def get_context_data(self, **kwargs):
        inv = Inventory.objects.filter(id=self.get_object().pk).first()
        ctx = {'items': Item.get_inventory_items(inv)}
        return ctx

def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = MyUser.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, MyUser.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        return redirect('core:index')
    else:
        return render(request, 'roleplay_user_and_login/invalid_link.html')

forum_project/forum/templates/roleplay_user_and_login/acc_active_email.html
{% autoescape off %}  
Hi {{ user.username }},
Please click on the link to confirm your registration,
http://{{ domain }}{% url 'roleplay_user_and_login:activate' uidb64=uid token=token %}
{% endautoescape %}

forum_project/forum/templates/roleplay_user_and_login/cabinet.html
{% extends 'base.html' %}
{% block title %}Cabinet{% endblock %}
{% block content %}
    <style>
    h1{
        color: white;
    }
    p{
        color: white;
    }
    
    </style>
    {% if user.is_authenticated %}
        <h1 >Hello {{user}}</h1>
        <h1> Number of comments: {{number_of_comments}} </h1>
        <h1>Inventory:</h1>
        {% if inventory%}
            {% for inv in inventory %}
                <a href="/inventory/{{inv.id}}">{{inv.project.name}}</a>
            {% endfor %}
        {% else %}
            <p>
                No items here
            </p>
        {% endif %}
        
    {% endif %}
{% endblock content %}

forum_project/forum/templates/roleplay_user_and_login/confirm_email.html
{% extends 'base.html' %}
{% block content %}
    <style>
    p{
        color:white;
    }
    </style>
    <p>'Please confirm your email address to complete the registration'</p>
{% endblock content %}

forum_project/forum/templates/roleplay_user_and_login/invalid_link.html
{% extends 'base.html' %}
{% block content %}
    <style>
    p{
        color:white;
    }
    </style>
    <p>Activation link is invalid!</p>
{% endblock content %}

forum_project/forum/templates/roleplay_user_and_login/inventory.html
{% extends 'base.html' %}
{% block title %}Inventory{% endblock %}
{% block content %}
    <style>
    h1{
        color: White;
    }
    </style>
    {% for item in items %}
        <p>{{item.name}}</>
    {% endfor %}
{% endblock content %}

forum_project/forum/templates/roleplay_user_and_login/login.html
{% extends 'base.html' %}
{% block content %}
<style>
    h2{
        color: white;
    }
    ul{
        color: white;
    }
    label{
        color: white;
    }
</style>
<h2>Login</h2>
<form method="post">
    {% csrf_token %}
    {{ form.non_field_errors }}
    <div class="fieldWrapper">
        {{ form.username.errors }}
        <label for="{{ form.username.id_for_label }}">Username:</label>
        {{ form.username }}
    </div>
    <div class="fieldWrapper">
        {{ form.password.errors }}
        <label for="{{ form.password.id_for_label }}">Password:</label>
        {{ form.password }}
    </div>
    <button type="submit">Login</button>
</form>
{% endblock content %}

forum_project/forum/templates/roleplay_user_and_login/pw_reset.html
{% extends "base.html" %}
{% block content %}
<style>
p{
    color:white;
}
input{
    color:black;
}
</style>
<p>Please specify your email address to receive instructions for resetting it.</p>

<form action="" method="post">
    <div style="display:none">
        <input type="hidden" value="{{ csrf_token }}" name="csrfmiddlewaretoken">
    </div>
    {{ form.email.errors }}
    <p><label for="id_email">E-mail address:</label> {{ form.email }} <input type="submit" value="Reset password" /></p>
</form>
{% endblock %}

forum_project/forum/templates/roleplay_user_and_login/pw_reset_done.html
{% extends 'base.html' %}
{% block content %}
<style>
    p{
        color:white;
    }
</style>
<div class="container">
    <p>
        Ми відправили вам інструкцію по встановленню нового паролю на вказаний адрес електронної пошти(якщо в нашій базі даних є такий адрес). 
        Ви повинні отримати її в найближчому часі.
        Якщо ви не отримали лист, будь ласка, переконайтесь, що ви ввели адресу з якою
        ви були зареєстровані, і перевірте папку з спамом.
    </p>
</div>

{% endblock content %}

forum_project/forum/templates/roleplay_user_and_login/signup.html
{% extends 'base.html' %}
{% block title %}Signup{% endblock %}
{% block content %}
    <style>
    h2{
        color: white;
    }
    ul{
        color: white;
    }
    label{
        color: white;
    }
    span{
        color: white;
    }
</style>
    <h2>Sign up</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Sign up</button>
    </form>
{% endblock %}