forum_project/apps/core/urls.py
from .views import ArticlesView, MainPageView, ArticleView
from django.urls import path, include
from django.views.generic import TemplateView


app_name = 'core'
urlpatterns = [
    path('', MainPageView.as_view(), name='index'),
    path('articles/<slug:slug>', ArticleView.as_view(), name='articles-article'),
    path('articles/', ArticlesView.as_view(), name='articles'),
]

forum_project/apps/roleplay_user_and_login/urls.py
from .views import RegistrationView, CabinetView, InventoryView, LoginView, LogoutView, activate
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView


app_name = 'roleplay_user_and_login'
urlpatterns = [
	path('login/', LoginView.as_view(), name='login'),
	path('logout/', LogoutView.as_view(), name='logout'),
	path('signup/', RegistrationView.as_view(), name='signup'),
	path('activate/<uidb64>/<token>/', activate, name='activate'),  
	path('reset/', auth_views.PasswordResetView.as_view(
		template_name='roleplay_user_and_login/pw_reset.html',
		success_url='done/'
	), name='reset'),
	path('reset/done/', TemplateView.as_view(
		template_name='roleplay_user_and_login/pw_reset_done.html'
	), name='reset_done'),
	path('cabinet/', CabinetView.as_view(), name='cabinet'),
	path('inventory/<int:pk>', InventoryView.as_view(), name='inventory'),
	path('', include('django.contrib.auth.urls'))
]

forum_project/forum/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.core.urls')),
    path('api/v1/', include('apps.api.v1.urls')),
    path('', include('apps.roleplay_user_and_login.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

forum_project/apps/core/models.py
from django.db import models
from autoslug import AutoSlugField


class Article(models.Model):
	title = models.TextField(max_length=255)
	text = models.TextField()
	image = models.ImageField(upload_to='Article_images', blank=True, null=True)
	slug = AutoSlugField(populate_from='title', null=True, unique=True, allow_unicode=True)

	updated = models.DateTimeField(auto_now=True)
	created = models.DateTimeField(auto_now_add=True)

	@classmethod
	def find_by_slug(cls, slug):
		return cls.objects.filter(slug=slug).first()

	def get_number_of_comments(self):
		return len(Comment.find_by_art(self))

	def __str__(self):
		return f"{self.title}, {self.title}"

	def save(self, *args, **kwargs):
		self.slug = None
		super().save(*args, **kwargs)


class Comment(models.Model):
	article = models.ForeignKey(to=Article, on_delete=models.CASCADE, blank=True, null=True)
	user = models.CharField(max_length=255, blank=True, null=True)
	text = models.TextField()
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)

	@classmethod
	def find_by_art(cls, article):
		return cls.objects.filter(article=article)

forum_project/apps/core/forms.py
from django import forms
from ..core.models import Comment, Article


class CommentForm(forms.ModelForm):
	text = forms.TextInput()

	class Meta(object):
		model = Comment
		fields = '__all__'

class ArticleForm(forms.ModelForm):
	class Meta(object):
		model = Article
		fields = ('title', 'text', 'image', )

forum_project/apps/core/views.py
from django.shortcuts import render
from .models import Article, Comment
from ..core.forms import CommentForm, ArticleForm
from django.views.generic import View, TemplateView, ListView, DetailView, RedirectView, CreateView
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect
from django.urls import reverse
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage


class MainPageView(CreateView):
	template_name = 'core/main_page.html'
	form_class = ArticleForm
	model = Article
	success_url = ''

	def get_context_data(self, **kwargs):
		f_articles = Article.objects.all()
		paginator = Paginator(object_list=f_articles.order_by('-created'), per_page=5)
		page = self.request.GET.get('page')
		try:
			articles = paginator.page(page)
		except PageNotAnInteger:
			articles = paginator.page(1)
		except EmptyPage:
			articles = paginator.page(paginator.numcpages)
		context = ({'articles': articles, 'number_of_posts': len(f_articles), 'form':self.form_class})
		return context

	def form_valid(self, form):
		form.save()
		return render(self.request, self.template_name, self.get_context_data())

class ArticlesView(TemplateView):
	template_name = 'core/articles.html'

	def get_context_data(self, **kwargs):
		articles = Article.objects.all()
		paginator = Paginator(object_list=articles.order_by('-created'), per_page=15)
		page = self.request.GET.get('page')
		try:
			articles = paginator.page(page)
		except PageNotAnInteger:
			articles = paginator.page(1)
		except EmptyPage:
			articles = paginator.page(paginator.num_pages)
		return {'articles': articles}


class ArticleDetailView(DetailView):
	template_name = 'core/article.html'
	model = Comment

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		return context


class ArticleView(CreateView):
	template_name = 'core/article.html'
	form_class = CommentForm
	model = Article
	success_url = ''
	slug_field = 'slug'

	def get_context_data(self, **kwargs):
		art = self.get_object()
		comments = Comment.find_by_art(art)
		paginator = Paginator(object_list=comments.order_by('-created'), per_page=5)
		page = self.request.GET.get('page')
		try:
			comments = paginator.page(page)
		except PageNotAnInteger:
			comments = paginator.page(1)
		except EmptyPage:
			comments = paginator.page(paginator.num_pages)

		ctx = {'article': art, 'comments': comments}
		return ctx

	def form_valid(self, form):
		comment = form.save(commit=False)
		comment.article = Article.find_by_slug(self.get_object().slug)
		comment.user = self.request.user
		# do something here
		comment.save()
		return render(self.request, self.template_name, self.get_context_data())

forum_project/forum/templates/core/components/footer.html
<style>
.footer {
  position: fixed;
  left: 0;
  bottom: 0;
  width: 100%;
  background-color: #555152;;
  color: white;
  text-align: center;
}
</style>

<div class="footer">
  <p>Footer</p>
</div>

forum_project/forum/templates/core/components/header.html
<style>
    ul {
        list-style-type: none;
        margin: auto;
        padding: 0;
        overflow: hidden;
        background-color: #555152;
        sticky;
    }

    li {
        float: left;
    }
    li.right{
        float: right;
    }

    li a {
        display: block;
        color: #EFFFCD;
        text-align: center;
        padding: 14px 16px;
        text-decoration: none;
    }

    li a:hover {
        background-color: #2E2633;
    }
</style>
<header>
    <ul>
        <li><a class="active" href="{% url 'core:index' %}">Home</a></li>
        <li><a href="/articles">News</a></li>
        {% if user.is_authenticated %}
            <li class="right"><a href="{% url 'roleplay_user_and_login:logout' %}">Logout</a></li>
            <li class="right"><a href="{% url 'roleplay_user_and_login:cabinet' %}">Hello, {{user}}</a></li>
            {% if user.is_admin %}
                <li class = "right"><a href='/api/v1/article/'> Api </a></li>
                <li class = "right"><a href='/admin'> Admin panel </a></li>
            {% endif %}
        {% else %}
            <li class="right"><a href="/signup">Signup</a></li>
            
            <div class="modal fade" id="modalLoginForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
                aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content" style="background: #2a2829">
                        <div class="modal-header text-center"  style="background: #555152">
                            <h4 class="modal-title w-100 font-weight-bold" style="color: #f4f4f4;">Sign in</h4>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <form id="login-form" action="{% url 'roleplay_user_and_login:login' %}" method="post" enctype="multipart/form-data" style="background: #8a8a8a">
                            {% csrf_token %}
                            <div class="modal-body" style="background: #8a8a8a;">
                                <div id="div-login-msg" style="padding-bottom: 10px; color: #f4f4f4;"><div id="icon-login-msg" class="glyphicon glyphicon-chevron-right"></div>
                                    <span id="text-login-msg">Type your username and password.</span>
                                </div>
                                <div style="padding-bottom: 20px;">
                                    <input id="username" name = 'username' class="form-control" type="text" placeholder="Username" required>
                                </div>
                                <input id="password" name = 'password' class="form-control" type="password" placeholder="Password" required>
                            </div>
                            <div class="modal-footer">
                                <a href="{% url 'roleplay_user_and_login:reset'%}" style="color: #EFFFCD;">Forgot password?</a>
                                <div class="container" align="center">
                                    <button style="width: auto; background-color: #17a2b8;" type="submit" class="btn btn-primary btn-lg btn-block">Login</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>

            <div class="text-center">

                <li class="right"><a href="" data-toggle="modal" data-target="#modalLoginForm">Login</a></li>
            </div>
{% endif %}
    </ul>

</header>